#!/usr/bin/env perl
########################################################
# Adapted from Penetration Testing With Perl           #
# by Douglas Berdeaux                                  #
# Chapter 3 IEEE 802.3 Wired Network Mapping with Perl #
########################################################

=head1 SYNOPSIS

Identifies target hosts by MAC address. Looks up the Organisationally Unique Indentifier (OUI) component of the MAC address in the F<data/oui.txt> file provided by the L<IEEE|http://ieee.org>

=cut

use strict;
use warnings;

my $target_mac = shift or die "Usage\n\t./id_target <target_mac>\n";

printf "Address: %s, MAC Manufacturer: %s\n", $target_mac, oui_lookup($target_mac);

sub oui_lookup
{
  my $mac_address = shift;
  $mac_address =~ s/:/-/g;
  my $oui = substr $mac_address, 0, 8;

  open (my $oui_file, '<', 'data/oui.txt') or die $!;
  while (my $line = <$oui_file>)
  {
    if($line =~ /$oui/i)
    {
      my ($address, $manufacturer_name) = split /\t+/, $line;
      return "$manufacturer_name";
      last;
    }
  }
  return "Unknown";
}

